### ISSUE TITLE
Potential Race Condition in Simulation

### ISSUE THREAD

**Issue by Yuan-Mao** [black-parrot-hdk/zynq-parrot#32]
I am not sure if we can get race condition in the signal "this->p_awready" in the following line:

https://github.com/black-parrot-hdk/zynq-parrot/blob/8fafb5eee50f292754e9501fa215f2395791aa7c/cosim/include/common/bsg_axil.h#L202

In line 180 we set "this->p_awvalid" to 1 and check if "this->p_awready" is high to see if the handshaking will happen. However, if p_awready is actually a YUMI signal that depends on awvalid, is it possible that awready would be read and written at the same time slot?

For example, let's assume that in some time slot, "this->p_awready" will be high if "this->p_awvalid" is set to 1. Now if the simulator reads "this->p_awready" and gets 0 instead of 1 at line 202, the simulation will fail as the code in bsg_axil will think that the handshaking will not happen but actually it will.

**Comment by dpetrisko** [comment]
It’s against the protocol to have awready depend combinatorial on awvalid, so it should be fine

**Comment by Yuan-Mao** [comment]
I see. Didn't know that we cannot have combinational path between them.

**Comment by dpetrisko** [comment]
Yeah it’s part of the AXI spec. You can have 

always_ff @(posedge clk) awready <= awvalid 

but not

assign awready = awvalid

**Comment by Yuan-Mao** [comment]
Then is it okay to have combinatorial paths between a master interface and a client interface in a MUX/DEMUX?

Like in this line: https://github.com/black-parrot-hdk/black-parrot-subsystems/blob/main/axi/v/bsg_axil_demux.v#L135

If the reason behind the rule is to avoid long paths between AXI nodes, then perhaps the answer to the above question is no.

**Comment by dpetrisko** [comment]
If it wasn’t allowed to connected master and client then wires would be illegal :)

**Comment by Yuan-Mao** [comment]
So we don't need to do like, register all the AXI input before we process the data? Like putting a FIFO between m00 <-> s00, m01<->s00 in DEMUX?

**Comment by dpetrisko** [comment]
It’s not required by spec. It it were a timing path, we could add a buffer afterwards. The actual path from input to output in the mux is only <5 gate delays which is trivial compared to the rest of the design

**Comment by Yuan-Mao** [comment]
Got it. Thanks!
