### ISSUE TITLE
ZYNP FPGA model

### ISSUE THREAD

**Issue by Jeremy-Jia** [black-parrot-hdk/zynq-parrot#76]
Hi，I want to run [hammerblade-example](https://github.com/black-parrot-hdk/zynq-parrot/tree/master/cosim/hammerblade-example), BP with bsg_manycore mesh accelerator.
I want to know the exact minimal zynq fpga model needed and I'm worried the resources may not be enough.
Thanks.

**Comment by dpetrisko** [comment]
It is a fairly large design. We use the ultra96v2 board which has a xczu3eg-sbva484-1-e part

**Comment by dpetrisko** [comment]
Let me know if you have any further questions, thanks
