### ISSUE TITLE
Duplicate entries for basejump_stl in .gitmodules

### ISSUE THREAD

**Issue by muwyse** [black-parrot-hdk/zynq-parrot#85]
See: https://github.com/black-parrot-hdk/zynq-parrot/blob/f0ab399dc6d83dabe4fa2e6863ef7e9a78101647/.gitmodules#L31

Looks like this results in some warnings being thrown, but don't know if there are worse consequences. Should be cleaned up.

**Comment by dpetrisko** [comment]
fixed
