### ISSUE TITLE
make prep error (error: .gitmodules: patch does not apply)

### ISSUE THREAD

**Issue by minecraftdixit** [black-parrot-hdk/zynq-parrot#87]
**Hi,
I was doing the make prep command and it failed at this part showing makefile error related to patches is there any solution to this ,running on Ubuntu 22.04.4 LTS**
 

make gnudramfs_build
make[3]: Entering directory '/home/vboxuser/Desktop/zynq-parrot/software/import/black-parrot-sdk'
cat: /etc/centos-release: No such file or directory
#cd /home/vboxuser/Desktop/zynq-parrot/software/import/black-parrot-sdk/riscv-gnu-toolchain; git apply --ignore-whitespace --ignore-space-change /home/vboxuser/Desktop/zynq-parrot/software/import/black-parrot-sdk/patches/riscv-gnu-toolchain/*.patch
cd /home/vboxuser/Desktop/zynq-parrot/software/import/black-parrot-sdk/riscv-gnu-toolchain;  git apply --ignore-space-change --ignore-whitespace  /home/vboxuser/Desktop/zynq-parrot/software/import/black-parrot-sdk/patches/riscv-gnu-toolchain/*.patch
**error: patch failed: .gitmodules:13
error: .gitmodules: patch does not apply**
make[3]: *** [/home/vboxuser/Desktop/zynq-parrot/software/import/black-parrot-sdk/Makefile.tools:36: gnudramfs_build] Error 1
make[3]: Leaving directory '/home/vboxuser/Desktop/zynq-parrot/software/import/black-parrot-sdk'
make[2]: *** [/home/vboxuser/Desktop/zynq-parrot/software/import/black-parrot-sdk/Makefile.tools:80: /home/vboxuser/Desktop/zynq-parrot/software/import/black-parrot-sdk/install/touchfiles/tools/gnudramfs.ae9efcc33c4968f97ab89b4b13c7f6520b145f94] Error 2
make[2]: Leaving directory '/home/vboxuser/Desktop/zynq-parrot/software/import/black-parrot-sdk'
make[1]: *** [Makefile:42: sdk_lite] Error 2
make[1]: Leaving directory '/home/vboxuser/Desktop/zynq-parrot/software/import/black-parrot-sdk'
make: *** [Makefile:12: prep] Error 2

**Comment by dpetrisko** [comment]
The most likely cause is that the process was interrupted and then reran. You can either clean the directory by going into black-parrot-sdk and doing "make bleach_all", or commenting out the patch lines here: https://github.com/black-parrot-sdk/black-parrot-sdk/blob/168ac44ccb9d1478044c1d9f071dc4ba40b96d35/Makefile.tools#L35
